# Generated by Django 5.1.4 on 2024-12-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Womens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('img_alt', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Baby', 'Baby'), ('Cap', 'Cap'), ('Shoe', 'Shoe')], max_length=5)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='mens',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
