# Generated by Django 5.1.4 on 2024-12-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_womens_alter_mens_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='womens',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
