# Generated by Django 5.1.4 on 2024-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_womens_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mens',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mens',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='womens',
            name='image',
            field=models.ImageField(upload_to='images/{CATEGORIES_CHOICE}'),
        ),
        migrations.AlterField(
            model_name='womens',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
