# Generated by Django 5.1.4 on 2024-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mens_image_alter_mens_price_alter_womens_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mens',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='womens',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
