# Generated by Django 5.1.4 on 2024-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_womens_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='womens',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EURO'), ('₹', 'INR'), ('रु', 'NRP')], default='$', max_length=5),
        ),
    ]
